version: '3'
services:
  dhpg-webapp:
    build: .
    container_name: dhpg.webapp
    command: bash -c "npm i && tail -f /dev/null"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - "3000:3000"
